"""
Definition of models.
"""

from django.db import models

#class Predilabtable(models.Model):
#    Prestamo_Id=models.IntegerField(null=False)
#    Prestamo_GrupoId=models.IntegerField(null=False)
#    Grupo_AsignaturaId=models.IntegerField(null=False)
#    Asignatura_Nombre=models.CharField(max_length=80)
#    Prestamo_EquipoId=models.IntegerField(null=False)
#    Equipo_Inventario=models.CharField(max_length=150)
#    Equipo_Serial=models.CharField(max_length=150)
#    Equipo_Nombre=models.CharField(max_length=150)
#    Equipo_TipoId=models.IntegerField(null=False)
#    TipoE_Nombre=models.CharField(max_length=150)
#    Equipo_Interno=models.CharField(max_length=80)
#    MarcaE_Id=models.IntegerField(null=False)
#    Equipo_MarcaId=models.IntegerField(null=False)
#    MarcaE_Nombre=models.CharField(max_length=80)
#    Equipo_ModeloId=models.IntegerField(null=False)
#    ModeloE_Nombre=models.CharField(max_length=150)
#    Prestamo_EstadoId=models.IntegerField(null=False)
#    Prestamo_FechaInicio=models.DateField(null=True)
#    Prestamo_HoraInicio=models.TimeField(null=False)
#    Prestamo_fecha_hora_inicio=models.DateTimeField(null=False)
#    Prestamo_FechaFin=models.DateField(null=True)
#    Prestamo_HoraFin=models.TimeField(null=False)
#    Prestamo_fecha_hora_fin=models.DateTimeField(null=False)
#    Prestamo_Reporte=models.CharField(max_length=150)
#    Prestamo_ReporteFecha=models.DateField(null=True)
#    Prestamo_ReporteHora=models.TimeField(null=False)
#    Prestamo_ReporteDetalle=models.CharField(max_length=150)
#    ReporteAgrupado=models.CharField(max_length=150, null=False)
#    Prestamo_Cantidad=models.IntegerField(null=False)
#class Datos(models.Model):
#	texto = models.CharField(max_length=15)
#	valor = models.IntegerField()    
#class Predilabtable3(models.Model):
#    AñoI=models.IntegerField(null=False)
#    MesI=models.IntegerField(null=False)
#    NumSem=models.IntegerField(null=False)
#    Nprestamos=models.IntegerField(null=False)
#    Nrep=models.IntegerField(null=False)
#    fusi=models.IntegerField(null=False)
#    Bateria=models.IntegerField(null=False)
#    RR=models.IntegerField(null=False)
#    Sondas=models.IntegerField(null=False)
#    Multimetro=models.IntegerField(null=False)
#    Otros=models.IntegerField(null=False)
#    Generador=models.IntegerField(null=False)
#    Fuente=models.IntegerField(null=False)
#    TIPO_0=models.IntegerField(null=False)
#    TIPO_1=models.IntegerField(null=False)
#    TIPO_2=models.IntegerField(null=False)
#    TIPO_3=models.IntegerField(null=False)
#    TIPO_4=models.IntegerField(null=False)
#    TIPO_5=models.IntegerField(null=False)
#    TIPO_6=models.IntegerField(null=False)
#    TIPO_7=models.IntegerField(null=False)
#    Asignatura_0=models.IntegerField(null=False)
#    Asignatura_1=models.IntegerField(null=False)
#    Asignatura_2=models.IntegerField(null=False)
#    Asignatura_5=models.IntegerField(null=False)
#    Asignatura_6=models.IntegerField(null=False)
#    Asignatura_7=models.IntegerField(null=False)
#    Asignatura_8=models.IntegerField(null=False)
#    Asignatura_9=models.IntegerField(null=False)
#    Asignatura_10=models.IntegerField(null=False)
#    Asignatura_11=models.IntegerField(null=False)
#    Asignatura_12=models.IntegerField(null=False)
#    Asignatura_13=models.IntegerField(null=False)
#    Asignatura_14=models.IntegerField(null=False)
#    Asignatura_15=models.IntegerField(null=False)
#    Asignatura_16=models.IntegerField(null=False)
#    Asignatura_17=models.IntegerField(null=False)
#    Asignatura_18=models.IntegerField(null=False)
#    Asignatura_19=models.IntegerField(null=False)
#    # Prestamo_HoraFin=models.TimeField(null=False)
#    #Prestamo_fecha_hora_fin=models.DateTimeField(null=False)
#   # Prestamo_Reporte=models.CharField(max_length=150)
#class Predictable(models.Model):
#    Id_int=models.IntegerField(null=False)
#    Año=models.IntegerField(null=False)
#    Semana=models.IntegerField(null=False)
#    Resultados=models.IntegerField(null=False)
